# Lab 2- Performing indexing ,Slicing and Broadcasting  in Numpy

# Program 1- indexing in Numpy

In [7]:
import numpy as np
arr=np.arange(1,10,2)
print("Element of array",arr)
arr1=arr[np.array([4,0,2,-1,-2])]
print("Indexed Element of array arr:",arr1)

Element of array [1 3 5 7 9]
Indexed Element of array arr: [9 1 5 9 7]


In [9]:
arr1=np.arange(4)
print(arr1)
print(arr1[0])
print(arr1[1])
print(arr1[2])

[0 1 2 3]
0
1
2


In [10]:
arr=np.arange(12)
arr1=arr.reshape(3,4)
print(arr1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
print("Element index:",arr1[1,3])

Element index: 7


In [13]:
print("Element index:",arr1[2,1])

Element index: 9


In [14]:
print("Element index:",arr1[1,0])

Element index: 4


In [15]:
print("Element index:",arr1[0,2])

Element index: 2


In [18]:
print("Element index:",arr1[1,3])

Element index: 7


In [19]:
arr=np.arange(12)
arr
arr1=arr.reshape(2,2,3)
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [21]:
print("Element index:",arr1[0,1,0])

Element index: 3


In [28]:
print("Element index:",arr1[1,0,1])

Element index: 7


# Program 2-Slicing in Array

In [32]:
arr=np.arange(6)
arr
arr[1:5]

array([1, 2, 3, 4])

In [45]:
arr=np.arange(12)
arr
arr1=arr.reshape(3,4)
print(arr1)
print("\n")
print(arr1[1:2:,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[5 6]]


In [48]:
arr=np.arange(1,10)
arr
arr1=arr.reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
scalar= 10
result = arr1*scalar

In [52]:
print(result)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
